#!/bin/bash

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh does
#       not find so, but you have some other compatible shell such as ksh or
#       bash, then change the shebang line to use that shell, and "if" all shell
#       commands used below are compatible to that shell.
#
#   (2) Upstream projects from Gradle may not support all properties of this
#       script (if any).
#
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%\"${app_path##*/}\"}
    [ -h \"$app_path\" ]
do
    ls=$(ls -ld \"$app_path\")
    link=${ls#*' -> '}
    case $link in
    /*) app_path=$link ;;
    *) app_path=$APP_HOME$link ;;
    esac
done

APP_HOME=$(cd \"${APP_HOME}\" && pwd -P) || exit

PS1='\u@\h:\w\$ '
export CLASSPATH=\"$APP_HOME/gradle/wrapper/gradle-wrapper.jar:$CLASSPATH\"

# Determine the Java command to use in order to create the runtime environment.
if ! type -p java > /dev/null; then
    echo \"ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.\" >&2
    exit 1
fi

if ! type -p javac > /dev/null; then
    echo \"WARNING: JAVA_HOME is not set and no 'javac' command could be found in your PATH.\" >&2
fi

exec \"$JAVA_HOME/bin/java\" "-Dorg.gradle.appname=$APP0\" -classpath \"$CLASSPATH\" org.gradle.wrapper.GradleWrapperMain \"$@\"
